const splashPosition = {
    "Zac": "",
    "Olaf": "",
    "Ivern": "",
    "Jax": "",
    "Singed": "",
    "Jhin": "",
    "Zed": "",
    "Viego": "",
    "Pantheon": "",
    "Sylas": "",
    "Yone": "",
    "Ekko": "",
    "Swain": "",
    "LeeSin": "",
    "Twitch": "",
    "Lilia": "",
    "XinZhao": "",
    "Zyra": "",
    "Azir": "",
    "Akali": "",
    "Galio": "",
    "Kayn": "",
    "Renekton": "",
    "Ahri": "",
    "Viktor": "",
    "Gragas": "",
    "Graves": "",
    "Taliyah": "",
    "Malphite": "",
    "Neeko": "",
    "Yasuo": "",
    "Malzahar": "",
    "Jinx": "",
    "Aurora": "",
    "Leblanc": "",
    "Ezreal": "",
    "Syndra": "",
    "Ambessa": "",
    "Ashe": ""
};

export default splashPosition;